#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.103.113.124:3306/guli_cms?characterEncoding=utf-8&useSSL=false
#    data-username: root
#    data-password: root
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl